# Generated by Django 3.2.5 on 2021-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='date_ending',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='date_start',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
