# Generated by Django 3.2.5 on 2021-09-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_formal',
            field=models.BooleanField(default=False, verbose_name='是否是正式用户'),
        ),
    ]
